## Research Computing at Leeds {.smaller}
<!--
  - {{< var rc.team >}}
-->
- A centralised [Team](https://arc.leeds.ac.uk/about/team/) and service supporting researchers with research computing platforms, consultancy and training.
- We have capacity to help with developing funding proposals, recruiting specialists and can provide costed support to deliver research projects.
- For details please see our [Website]({{< var rc.website >}})
- For support and queries, please [send us a ticket via the IT Service Desk]({{< var rc.servicedesk >}})

::: {.notes}
- Read slide title and first point:
  - "Research Computing at Leeds is a..."
- Click the `Team` link.
- In the `Slide View` Web browser window a new tab should open showing the the `Research Computing Team Web Page`
- Find the tab and scroll down the Web page to show the current team...
- Introduce yourself:
  - "My name is..."
    - "I joined the team as a Research Software Engineer (RSE)..."
      - Say when.
    - "I am leading the training today."
- Ask helpers to introduce themselves.
- Close tab that openend and return to the `Speaker View` window.
- Read the second and third points:
  - "We have..."
- Click on the `Website` link.
- In the `Slide View` window a new tab should have open.
- Find this tab and scroll down the Website Home Page pointing out some sections/features:
  - Documentation
  - Search
  - Contact Us
- Close the Website tab and return to the `Speaker View` window.
- Move to the next slide.
:::
