---
title: "arctraining slides"
format:
  html:
    embed-resources: true
---

Public facing homepage for arctraining Quarto slides collection.

## Slides: 

Note: this page is under construction. As soon as the slides are available,
the link will be provided.

- [x] [HPC0: Linux 101](./linux101.qmd)
- [ ] [HPC0: Introduction to Linux for HPC](./hpc0.qmd)
- [x] [HPC1: Introduction to High Performance Computing](hpc1.qmd)
- [ ] HPC2: Applications and containers on HPC
- [ ] HPC3: Computer architectures and shared memory parallel programming
- [ ] HPC5: Introduction to GPU programming with CUDA
- [ ] HPC6: HPC for Life Sciences and Bioinformatics
- [ ] SWD1a: Introduction to Python programming
- [ ] SWD1b: Introduction to R programming
- [ ] SWD2: Version Control with Git and GitHub
- [x] [SWD3: Software development practices for Research](./swd3.qmd)
- [ ] SWD4: Cloud computing for Research
- [ ] SWD5: Scientific Python
- [ ] SWD6: High performance Python
- [ ] SWD7: Introduction to reproducible workflows in Python
